name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build \
            -t reactjs-app \
            --build-arg REACT_APP_NODE_ENV=production \
            --build-arg REACT_APP_SERVER_BASE_URL=${{ secrets.REACT_APP_SERVER_BASE_URL }} \
            .

      - name: Tag Docker Image
        run: docker tag reactjs-app farhajqureshi81/reactjs-app:latest

      - name: Push Docker Image to Docker Hub
        run: docker push farhajqureshi81/reactjs-app:latest
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: ðŸ›¡ï¸ Run Trivy FS Scan using Docker
        run: |
          echo "ðŸ” Trivy scanning started..."
          docker run --rm -v ${{ github.workspace }}:/project aquasec/trivy fs --severity HIGH,CRITICAL /project > trivy-fs-report.txt || true

      - name: ðŸ“¤ Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-fs-report
          path: trivy-fs-report.txt

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull farhajqureshi81/reactjs-app:latest

      - name: Delete old container
        run: docker rm -f reactjs-app-container || true

      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container farhajqureshi81/reactjs-app:latest
